<?php

namespace App\Services;

class CountryService
{
    /**
     * Get all countries in alphabetical order (Italian names).
     */
    public static function getCountries(): array
    {
        return [
            'AF' => 'Afghanistan',
            'AL' => 'Albania',
            'DZ' => 'Algeria',
            'AD' => 'Andorra',
            'AO' => 'Angola',
            'AG' => 'Antigua e Barbuda',
            'AR' => 'Argentina',
            'AM' => 'Armenia',
            'AU' => 'Australia',
            'AT' => 'Austria',
            'AZ' => 'Azerbaigian',
            'BS' => 'Bahamas',
            'BH' => 'Bahrein',
            'BD' => 'Bangladesh',
            'BB' => 'Barbados',
            'BY' => 'Bielorussia',
            'BE' => 'Belgio',
            'BZ' => 'Belize',
            'BJ' => 'Benin',
            'BT' => 'Bhutan',
            'BO' => 'Bolivia',
            'BA' => 'Bosnia ed Erzegovina',
            'BW' => 'Botswana',
            'BR' => 'Brasile',
            'BN' => 'Brunei',
            'BG' => 'Bulgaria',
            'BF' => 'Burkina Faso',
            'BI' => 'Burundi',
            'CV' => 'Capo Verde',
            'KH' => 'Cambogia',
            'CM' => 'Camerun',
            'CA' => 'Canada',
            'CF' => 'Repubblica Centrafricana',
            'TD' => 'Ciad',
            'CL' => 'Cile',
            'CN' => 'Cina',
            'CY' => 'Cipro',
            'CO' => 'Colombia',
            'KM' => 'Comore',
            'CG' => 'Congo',
            'CD' => 'Repubblica Democratica del Congo',
            'CR' => 'Costa Rica',
            'CI' => 'Costa d\'Avorio',
            'HR' => 'Croazia',
            'CU' => 'Cuba',
            'DK' => 'Danimarca',
            'DM' => 'Dominica',
            'DO' => 'Repubblica Dominicana',
            'EC' => 'Ecuador',
            'EG' => 'Egitto',
            'SV' => 'El Salvador',
            'AE' => 'Emirati Arabi Uniti',
            'ER' => 'Eritrea',
            'EE' => 'Estonia',
            'SZ' => 'Eswatini',
            'ET' => 'Etiopia',
            'FJ' => 'Figi',
            'PH' => 'Filippine',
            'FI' => 'Finlandia',
            'FR' => 'Francia',
            'GA' => 'Gabon',
            'GM' => 'Gambia',
            'GE' => 'Georgia',
            'DE' => 'Germania',
            'GH' => 'Ghana',
            'JM' => 'Giamaica',
            'JP' => 'Giappone',
            'DJ' => 'Gibuti',
            'JO' => 'Giordania',
            'GR' => 'Grecia',
            'GD' => 'Grenada',
            'GT' => 'Guatemala',
            'GN' => 'Guinea',
            'GW' => 'Guinea-Bissau',
            'GQ' => 'Guinea Equatoriale',
            'GY' => 'Guyana',
            'HT' => 'Haiti',
            'HN' => 'Honduras',
            'IN' => 'India',
            'ID' => 'Indonesia',
            'IR' => 'Iran',
            'IQ' => 'Iraq',
            'IE' => 'Irlanda',
            'IS' => 'Islanda',
            'IL' => 'Israele',
            'IT' => 'Italia',
            'KZ' => 'Kazakistan',
            'KE' => 'Kenya',
            'KG' => 'Kirghizistan',
            'KI' => 'Kiribati',
            'KW' => 'Kuwait',
            'LA' => 'Laos',
            'LS' => 'Lesotho',
            'LV' => 'Lettonia',
            'LB' => 'Libano',
            'LR' => 'Liberia',
            'LY' => 'Libia',
            'LI' => 'Liechtenstein',
            'LT' => 'Lituania',
            'LU' => 'Lussemburgo',
            'MK' => 'Macedonia del Nord',
            'MG' => 'Madagascar',
            'MW' => 'Malawi',
            'MY' => 'Malesia',
            'MV' => 'Maldive',
            'ML' => 'Mali',
            'MT' => 'Malta',
            'MA' => 'Marocco',
            'MH' => 'Isole Marshall',
            'MR' => 'Mauritania',
            'MU' => 'Mauritius',
            'MX' => 'Messico',
            'FM' => 'Micronesia',
            'MD' => 'Moldavia',
            'MC' => 'Monaco',
            'MN' => 'Mongolia',
            'ME' => 'Montenegro',
            'MZ' => 'Mozambico',
            'MM' => 'Myanmar',
            'NA' => 'Namibia',
            'NR' => 'Nauru',
            'NP' => 'Nepal',
            'NI' => 'Nicaragua',
            'NE' => 'Niger',
            'NG' => 'Nigeria',
            'NO' => 'Norvegia',
            'NZ' => 'Nuova Zelanda',
            'OM' => 'Oman',
            'NL' => 'Paesi Bassi',
            'PK' => 'Pakistan',
            'PW' => 'Palau',
            'PA' => 'Panama',
            'PG' => 'Papua Nuova Guinea',
            'PY' => 'Paraguay',
            'PE' => 'Perù',
            'PL' => 'Polonia',
            'PT' => 'Portogallo',
            'QA' => 'Qatar',
            'GB' => 'Regno Unito',
            'CZ' => 'Repubblica Ceca',
            'RO' => 'Romania',
            'RW' => 'Ruanda',
            'RU' => 'Russia',
            'KN' => 'Saint Kitts e Nevis',
            'LC' => 'Santa Lucia',
            'VC' => 'Saint Vincent e Grenadine',
            'WS' => 'Samoa',
            'SM' => 'San Marino',
            'ST' => 'São Tomé e Príncipe',
            'SA' => 'Arabia Saudita',
            'SN' => 'Senegal',
            'RS' => 'Serbia',
            'SC' => 'Seychelles',
            'SL' => 'Sierra Leone',
            'SG' => 'Singapore',
            'SK' => 'Slovacchia',
            'SI' => 'Slovenia',
            'SB' => 'Isole Salomone',
            'SO' => 'Somalia',
            'ZA' => 'Sudafrica',
            'SS' => 'Sudan del Sud',
            'ES' => 'Spagna',
            'LK' => 'Sri Lanka',
            'US' => 'Stati Uniti',
            'SD' => 'Sudan',
            'SR' => 'Suriname',
            'SE' => 'Svezia',
            'CH' => 'Svizzera',
            'TJ' => 'Tagikistan',
            'TZ' => 'Tanzania',
            'TH' => 'Tailandia',
            'TL' => 'Timor Est',
            'TG' => 'Togo',
            'TO' => 'Tonga',
            'TT' => 'Trinidad e Tobago',
            'TN' => 'Tunisia',
            'TR' => 'Turchia',
            'TM' => 'Turkmenistan',
            'TV' => 'Tuvalu',
            'UA' => 'Ucraina',
            'UG' => 'Uganda',
            'HU' => 'Ungheria',
            'UY' => 'Uruguay',
            'UZ' => 'Uzbekistan',
            'VU' => 'Vanuatu',
            'VA' => 'Vaticano',
            'VE' => 'Venezuela',
            'VN' => 'Vietnam',
            'YE' => 'Yemen',
            'ZM' => 'Zambia',
            'ZW' => 'Zimbabwe',
        ];
    }

    /**
     * Get country name by code.
     */
    public static function getCountryName(string $code): ?string
    {
        $countries = self::getCountries();
        return $countries[$code] ?? null;
    }

    /**
     * Get countries sorted alphabetically by name.
     */
    public static function getCountriesSorted(): array
    {
        $countries = self::getCountries();
        asort($countries);
        return $countries;
    }
}